---
spring:          
  data:
    mongodb:
      host: localhost
      port: 27017
      database: employee-db
  

okta:
  oauth2:
    client-id: 0oa50tmsxlBeUKcQ25d7
    client-secret: 0WZ7SenvM8toExEuGQI90PXRee_zU69I_ONGwT2q
    issuer:   https://dev-33619804.okta.com/oauth2/default
    #redirect-uri: /authorization-code/callback
    #rolesClaim: groups
  apis:
    baseUri: https://dev-33619804.okta.com
    userEndPoint: /api/v1/users

